### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KimmyDavis** [komoireashiraf/CSS-Lessons#1]
Hey... Would you mind including **combinators** too...

**Comment by komoireashiraf** [comment]
> Hey... Would you mind including **combinators** too...

okay noted, i will surely do

**Comment by komoireashiraf** [comment]
> > Hey... Would you mind including **combinators** too...
> 
> okay noted, i will surely do

please check out file name 'more.css' its a continuations of the last uploaded. thank you
